protected/models/Server.php
<?php

/**
 * This is the model class for table "server".
 *
 * The followings are the available columns in table 'server':
 * @property string $id
 * @property string $name
 * @property string $ip
 * @property string $enableHttpOutput
 * @property string $enableUdpOutput
 * @property string $keepHttpActive
 * @property string $externalIp
 * @property string $urlInputProcesses
 *
 * The followings are the available model relations:
 * @property Adapter[] $adapters
 * @property Channel[] $channels
 * @property Stream[] $streams
 *
 * @property string $relayConfigFile
 * @property bool $haveUrlInput
 * @property bool $haveRelay
 * @property string $outputsList
 */
class Server extends MyActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'server';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name, ip', 'required'),
			array('name', 'length', 'max'=>255),
			array('ip, externalIp, urlInputProcesses', 'length', 'max'=>45),
            array('enableHttpOutput, enableUdpOutput, keepHttpActive', 'length', 'max'=>1),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, name, ip, enableHttpOutput, enableUdpOutput, keepHttpActive, externalIp', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'adapters' => array(self::HAS_MANY, 'Adapter', 'serverId'),
            'channels' => array(self::HAS_MANY, 'Channel', 'serverId'),
			'streams' => array(self::HAS_MANY, 'Stream', 'serverId'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'name' => Yii::t('models', 'Имя'),
			'ip' => Yii::t('models', 'IP адрес'),
            'enableHttpOutput' => Yii::t('models', 'HTTP вывод'),
            'enableUdpOutput' => Yii::t('models', 'UDP вывод'),
            'keepHttpActive' => Yii::t('models', 'Не отключать неактивные вводы (для HTTP вывода)'),
            'externalIp' => Yii::t('models', 'Внешний IP (для HTTP серверов за NAT)'),
            'outputsList' => Yii::t('models', 'Выводы'),
            'urlInputProcesses' => Yii::t('models', 'Количество URL Input процесов'),
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('ip',$this->ip,true);
        $criteria->compare('enableHttpOutput',$this->enableHttpOutput);
        $criteria->compare('enableUdpOutput',$this->enableUdpOutput);
        $criteria->compare('keepHttpActive',$this->keepHttpActive);
        $criteria->compare('externalIp',$this->externalIp);
        $criteria->compare('urlInputProcesses',$this->urlInputProcesses);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Server the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

    public function getRelayConfigFile()
    {
        return Yii::app()->controller->renderPartial('//servers/_relayConfig', array('server' => $this), true);
    }

    public function getUrlInputsConfigFile($num)
    {
        return Yii::app()->controller->renderPartial('//servers/_urlConfig', array('server' => $this, 'num' => $num), true);
    }

    public function getHaveUrlInput()
    {
        foreach ($this->streams as $stream)
        {
            if ($stream->type == Stream::TYPE_URL && $stream->canCast)
                return true;
        }
        return false;
    }

    public function getHaveRelay()
    {
        foreach ($this->channels as $channel)
        {
            if ($channel->canCast && !$channel->directCast)
                return true;
        }
        return false;
    }

    public function getOutputsList()
    {
        $outputs = array();
        if ($this->enableHttpOutput)
            $outputs[] = 'HTTP';
        if ($this->enableUdpOutput)
            $outputs[] = 'UDP';
        if (count($outputs) == 0)
            return Yii::t('gen', 'Нет');
        return implode(', ', $outputs);
    }

    public function delete()
    {
        $retval = false;
        $useTransaction = !$this->dbConnection->currentTransaction;
        if ($useTransaction)
            $transaction = $this->dbConnection->beginTransaction();
        try
        {
            foreach ($this->adapters as $adapter)
            {
                if (!$adapter->delete())
                    throw new CException('Error deleting adapter '.$adapter->id);
            }
            foreach ($this->channels as $channel)
            {
                if (!$channel->delete())
                    throw new CException('Error deleting channel '.$channel->id);
            }
            foreach ($this->streams as $stream)
            {
                if (!$stream->delete())
                    throw new CException('Error deleting stream '.$stream->id);
            }
            $retval = parent::delete();
            if ($useTransaction)
                $transaction->commit();
        }
        catch(Exception $e)
        {
            Yii::log('Error deleting channel '.$this->id.', caught exception: '.$e->getMessage(), CLogger::LEVEL_ERROR);
            if ($useTransaction)
                $transaction->rollback();
        }
        return $retval;
    }
}

protected/controllers/MonitoringController.php
<?php

class MonitoringController extends Controller {

    public function actionEvent()
    {
//        $server = Server::model()->findByAttributes(array('ip' => Yii::app()->request->userHostAddress));
//        /* @var $server Server */
//        if (!$server)
//            throw new CHttpException(403);
        $rawData = file_get_contents('php://input');
        $data = json_decode($rawData, true);
        if (!$data)
            throw new CException('Error decoding JSON event data');
        foreach($data as $row)
        {
            $event = new MonitoringEvent();
            $event->attributes = $row;
            $event->scrambled = intval($event->scrambled);
            $event->onair = intval($event->onair);
            $event->fallback = intval($event->fallback);
//            Yii::log(var_export($event->attributes, true), CLogger::LEVEL_ERROR);
            if (!$event->save())
                Yii::log('Monitoring event not saved, raw data was: '.PHP_EOL.'"'.$rawData.'"'.PHP_EOL.', row was: '.PHP_EOL.'"'.var_export($row, true).'"', CLogger::LEVEL_ERROR);
        }
    }

    public function filters()
    {
        return array(
            'accessControl',
        );
    }

    public function accessRules()
    {
        return array(
            array('allow', 'actions' => 'event'),
            array('allow', // allow authenticated users to access all actions
                'users'=>array('@'),
            ),
            array('deny'),
        );
    }

}

protected/controllers/ServersController.php
<?php

class ServersController extends Controller
{
    public function actionIndex()
    {
        $server = new Server('search');
        $server->unsetAttributes();
        if (isset($_REQUEST['Server']))
            $server->attributes = $_REQUEST['Server'];
        $this->render('index', array('model' => $server));
    }

    public function actionView($id, $showConfig = false)
    {
        $server = self::loadModel(array('id' => $id));
        $this->render('view', array('model' => $server, 'showConfig' => $showConfig));
    }

    public function actionUpdate($id)
    {
        $server = self::loadModel(array('id' => $id));
        if (isset($_POST['Server']))
        {
            $server->attributes = $_POST['Server'];
            $server->save();
        }
        $this->render('update', array('model' => $server));
    }

    public function actionCreate()
    {
        $server = new Server();
        if (isset($_POST['Server']))
        {
            $server->attributes = $_POST['Server'];
            if ($server->save())
                $this->redirect(array('/servers/view', 'id' => $server->id));
        }
        $this->render('create', array('model' => $server));
    }

    public function actionDelete($id)
    {
        $server = self::loadModel(array('id' => $id));
        if (!$server->delete())
            throw new CHttpException(500);
    }

    public function actionGetConfigs()
    {
        $server = Server::model()->findByAttributes(array('ip' => Yii::app()->request->userHostAddress));
        /* @var $server Server */
        if (!$server)
            throw new CHttpException(403);
        $tmpName = tempnam(sys_get_temp_dir(), 'aconf');
        $zip = new ZipArchive;
        $zip->open($tmpName, ZipArchive::CREATE || ZipArchive::OVERWRITE);
        foreach ($server->adapters as $adapter)
        {
            if ($adapter->dvbTranspoder)
            {
                $fileName = 'a'.$adapter->num.'.lua';
                $zip->addFromString($fileName, $adapter->configFile);
            }
        }
        if ($server->haveRelay)
            $zip->addFromString('relay.lua', $server->relayConfigFile);
        if ($server->haveUrlInput)
            for ($i = 0; $i < $server->urlInputProcesses; $i++)
                $zip->addFromString('urlInput_'.$i.'.lua', $server->getUrlInputsConfigFile($i));
        $zip->close();
        header("Content-type: application/octet-stream");
        header("Content-Disposition: attachment; filename=\"server.zip\"");
        echo file_get_contents($tmpName);
        unlink($tmpName);
        Yii::app()->end();
    }

    public function actionGetZabbixDiscovery()
    {
        $server = Server::model()->findByAttributes(array('ip' => Yii::app()->request->userHostAddress));
        /* @var $server Server */
        if (!$server)
            throw new CHttpException(403);
        $ret = array();
        foreach ($server->adapters as $adapter)
        {
            if ($adapter->dvbTranspoder)
                $ret[] = array(
                    '{#MAC}' => $adapter->mac,
                    '{#TRANS_NAME}' => $adapter->dvbTranspoder->description
                );
        }
        echo json_encode($ret, JSON_UNESCAPED_UNICODE);
        Yii::app()->end();
    }

    public static function loadModel($options)
    {
        $model = Server::model()->findByAttributes($options);
        if (!$model)
            throw new CHttpException(404);
        return $model;
    }

    public function filters()
    {
        return array(
            'ajaxOnly + delete',
            'accessControl',
        );
    }

    public function accessRules()
    {
        return array(
            array('allow', 'actions' => array('getConfigs', 'getZabbixDiscovery')),
            array('allow', // allow authenticated users to access all actions
                'users'=>array('@'),
            ),
            array('deny'),
        );
    }
}

protected/views/servers/_form.php
<?php
/* @var $this ServerController */
/* @var $model Server */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'server-_form-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note"><?= Yii::t('models', 'Поля с {*} обязательны к заполнению', array('{*}' => '<span class="required">*</span>')); ?></p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name'); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

    <div class="row">
        <?php echo $form->labelEx($model,'ip'); ?>
        <?php echo $form->textField($model,'ip'); ?>
        <?php echo $form->error($model,'ip'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model,'enableHttpOutput'); ?>
        <?php echo $form->checkBox($model,'enableHttpOutput'); ?>
        <?php echo $form->error($model,'enableHttpOutput'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model,'keepHttpActive'); ?>
        <?php echo $form->checkBox($model,'keepHttpActive'); ?>
        <?php echo $form->error($model,'keepHttpActive'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model,'enableUdpOutput'); ?>
        <?php echo $form->checkBox($model,'enableUdpOutput'); ?>
        <?php echo $form->error($model,'enableUdpOutput'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model,'externalIp'); ?>
        <?php echo $form->textField($model,'externalIp'); ?>
        <?php echo $form->error($model,'externalIp'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model,'urlInputProcesses'); ?>
        <?php echo $form->textField($model,'urlInputProcesses'); ?>
        <?php echo $form->error($model,'urlInputProcesses'); ?>
    </div>

	<div class="row buttons">
		<?php echo CHtml::submitButton(Yii::t('app', 'Сохранить')); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/servers/_relayConfig.php
<?php
/**
 * @var $server Server
 */

$channels = $server->channels;


?>#!/usr/bin/env astra-4.0

if (init_all ~= nil) then -- check if monitoring is available
    event_request = "<?= $this->createAbsoluteUrl('/monitoring/event') ?>"
    event_request_interval = <?= Yii::app()->params['monitoringEventTimeout'] / 2 ?>
    init_all()
end

pidfile("/var/run/astra_relay.pid")
log.set({filename = "/var/log/astra/relay.log"})

<?php


foreach ($channels as $channel)
{
    if ($channel->canCast && !$channel->directCast)
    {
    ?>
make_channel({ -- <?= $channel->name ?> --
    name = "<?= $channel->name ?>",
    id = <?= $channel->id ?>,
    event = true,
    input = {
<?php
        foreach ($channel->streams as $stream)
        {
            if ($stream->canCast)
            {
                echo '        "'.AstraUrl::fromString($stream->internalCastUrl)->setUdpInterface($server->ip)->addParam('id='.$stream->id)->asString().'", -- '.$stream->name.PHP_EOL;
            }
        }
        // @todo: Смотреть во все, без useBackup ставить в конец
        if ($stream->useBackup)
        {
            echo '        "file:///home/abram/matras.ts#loop&id=fallback",', PHP_EOL;
        }
?>
    },

    output = {
<?php

        if ($stream->channel->server->enableHttpOutput)
            echo '        "', $stream->channel->outputHttpUrl, '",', PHP_EOL;
        if ($stream->channel->server->enableUdpOutput)
            echo '        "', $stream->channel->outputUdpUrl, '",', PHP_EOL;

        ?>
    } -- output
})

<?php
    }
}

?>

protected/views/servers/_urlConfig.php
<?php
/**
 * @var $server Server
 * @var $this Controller
 * @var $num int
 */

$streams = $server->streams;


?>#!/usr/bin/env astra-4.0

if (init_all ~= nil) then -- check if monitoring is available
    event_request = "<?= $this->createAbsoluteUrl('/monitoring/event') ?>"
    event_request_interval = <?= Yii::app()->params['monitoringEventTimeout'] / 2 ?>
    init_all()
end

pidfile("/var/run/astra_urlInput_<?= $num ?>.pid")
log.set({filename = "/var/log/astra/urlInput_<?= $num ?>.log"})

<?php

$i = 0;

foreach ($streams as $stream)
{
    if ($stream->canCast && $stream->type == Stream::TYPE_URL && ($i % $server->urlInputProcesses == $num))
    {
        ?>
make_channel({ -- <?= $stream->name ?> --
    name = "<?= $stream->channel->directCast ? $stream->channel->name : $stream->name ?>",
<?php
        if ($stream->channel->directCast)
        {
            ?>
    id = <?= $stream->channelId ?>,
    event = true,
<?php } ?>
    input = {
<?php
        echo '        "'.AstraUrl::fromString($stream->url)->addParam('id='.$stream->id)->asString().'", -- '.$stream->name.PHP_EOL;
        if ($stream->channel->directCast && $stream->useBackup)
            echo '        "file:///home/abram/matras.ts#loop&id=fallback",';
        ?>

    },

output = {
<?php
        if ($stream->channel->directCast)
        {
            if ($stream->channel->server->enableHttpOutput)
                echo '        "', $stream->channel->outputHttpUrl, '",', PHP_EOL;
            if ($stream->channel->server->enableUdpOutput)
                echo '        "', $stream->channel->outputUdpUrl, '",', PHP_EOL;
        }
        else
            echo '        "', $stream->internalCastUrl, '",', PHP_EOL;
        ?>
    } -- output
})

    <?php
    }
    $i++;
}

?>

protected/views/servers/create.php
<?php
/**
 * @var $this ServersController
 * @var $model Server
 */

$this->breadcrumbs=array(
    Yii::t('menu', 'Список серверов') => array('/servers/index'),
);

$this->pageHeader = Yii::t('menu','Создание сервера');
?>
<p>
    <?php
    $this->renderPartial('_form', array('model' => $model));
    ?>
</p>

protected/views/servers/index.php
<?php
/**
 * @var $this ServersController
 * @var $model Server
 */

$this->pageHeader = Yii::t('menu','Список серверов');
?>
<p>
    <?php
    $dataProvider=$model->search();

    $this->widget('zii.widgets.grid.CGridView', array(
        'dataProvider'=>$dataProvider,
        'filter'=>$model,
        'columns' => array(
            'name',
            'ip',
            array(
                'name' => 'outputsList',
                'filter' => false,
            ),
            'urlInputProcesses',
            array(
                'class'=>'CButtonColumn',
            ),
        ),
    ));

    $this->widget('zii.widgets.jui.CJuiButton',array(
            'buttonType'=>'link',
            'name' => 'create',
            'caption' => Yii::t('models', 'Создать'),
            'url' => array('create'),
        )
    );

    ?>
</p>

protected/views/servers/update.php
<?php
/**
 * @var $this ServersController
 * @var $model Server
 */

$this->breadcrumbs=array(
    Yii::t('menu', 'Список серверов') => array('/servers/index'),
);

$this->pageHeader = Yii::t('menu','Редактирование сервера {NAME}', array('{NAME}' => $model->name));
?>
<p>
    <?php
    $this->renderPartial('_form', array('model' => $model));
    ?>
</p>

protected/views/servers/view.php
<?php
/**
 * @var $this ServersController
 * @var $model Server
 * @var $showConfig bool
 */

$this->breadcrumbs=array(
    Yii::t('menu', 'Список серверов') => array('/servers/index'),
);

$this->pageHeader = Yii::t('menu','Просмотр сервера {NAME}', array('{NAME}' => $model->name));
?>
<p>
    <?php
    $this->widget('zii.widgets.CDetailView', array(
        'data'=>$model,
        'attributes'=>array(
            'id',
            'ip',
            'name',
            'outputsList',
            'urlInputProcesses',
        ),
    ));

    $this->widget('zii.widgets.jui.CJuiButton',array(
            'buttonType'=>'link',
            'name' => 'update',
            'caption' => Yii::t('models', 'Редактировать'),
            'url' => array('update', 'id' => $model->id),
        )
    );


    if ($showConfig)
    {
        echo CHtml::tag('h2', array(),Yii::t('menu', 'Конфигурация'));
        if ($model->haveUrlInput)
        {
            echo CHtml::tag('h3', array(), Yii::t('app', 'URL входы:'));
            for ($i = 0; $i < $model->urlInputProcesses; $i++)
                echo CHtml::textArea('astraUrlInputsConfig_'.$i, $model->getUrlInputsConfigFile($i), array('rows' => 25, 'cols' => 80, 'readonly'=>true));
        }
        if ($model->haveRelay)
        {
            echo CHtml::tag('h3', array(), Yii::t('app', 'Сборка и трансляция резервированных каналов:'));
            echo CHtml::textArea('astraRelayConfig', $model->relayConfigFile, array('rows' => 25, 'cols' => 80, 'readonly'=>true));
        }
            }
    else
    {
        $this->widget('zii.widgets.jui.CJuiButton',array(
                'buttonType'=>'link',
                'name' => 'showConfig',
                'caption' => Yii::t('models', 'Показать конфигурацию'),
                'url' => array('/servers/view', 'id' => $model->id, 'showConfig' => true),
            )
        );
    }

    ?>
</p>