protected/controllers/AdaptersController.php
<?php

class AdaptersController extends Controller
{
    public function actionIndex()
    {
        $adapter = new Adapter('search');
        $adapter->unsetAttributes();
        if (isset($_REQUEST['Adapter']))
            $adapter->attributes = $_REQUEST['Adapter'];
        $this->render('index', array('model' => $adapter));
    }

    public function actionView($id, $showConfig = false)
    {
        $adapter = self::loadModel(array('id' => $id));
        $this->render('view', array('model' => $adapter, 'showConfig' => $showConfig));
    }

    public function actionUpdate($id)
    {
        $adapter = self::loadModel(array('id' => $id));
        if (isset($_POST['Adapter']))
        {
            $adapter->attributes = $_POST['Adapter'];
            if (!$adapter->device)
                $adapter->device = null;
            $adapter->save();
        }
        $this->render('update', array('model' => $adapter));
    }

    public function actionCreate()
    {
        $adapter = new Adapter();
        if (isset($_POST['Adapter']))
        {
            $adapter->attributes = $_POST['Adapter'];
            if ($adapter->save())
                $this->redirect(array('/adapters/view', 'id' => $adapter->id));
        }
        $this->render('create', array('model' => $adapter));
    }

    public function actionDelete($id)
    {
        $adapter = self::loadModel(array('id' => $id));
        if (!$adapter->delete())
            throw new CHttpException(500);
    }

    /**
     * @param $options
     * @return Adapter
     * @throws CHttpException
     */
    public static function loadModel($options)
    {
        $model = Adapter::model()->findByAttributes($options);
        if (!$model)
            throw new CHttpException(404);
        return $model;
    }

    public function filters()
    {
        return array(
            'ajaxOnly + delete',
            'accessControl',
        );
    }

    public function accessRules()
    {
        return array(
            array('allow', // allow authenticated users to access all actions
                'users'=>array('@'),
            ),
            array('deny'),
        );
    }

}

protected/controllers/ChannelsController.php
<?php

class ChannelsController extends Controller
{
    public function actionIndex($editMode = 0)
    {
        $channel = new Channel('search');
        $channel->unsetAttributes();
        if (isset($_REQUEST['Channel']))
            $channel->attributes = $_REQUEST['Channel'];
        $this->render('index', array('model' => $channel, 'editMode' => $editMode));
    }

    public function actionView($id)
    {
        $channel = self::loadModel(array('id' => $id));
        $this->render('view', array('model' => $channel));
    }

    public function actionUpdate($id)
    {
        $channel = self::loadModel(array('id' => $id));
        if (isset($_POST['Channel']))
        {
            $channel->attributes = $_POST['Channel'];
            $channel->save();
        }
        $this->render('update', array('model' => $channel));
    }

    public function actionCreate()
    {
        $channel = new Channel();
        $channel->num = $channel->dbConnection->createCommand('SELECT MAX(num) FROM `channel`;')->queryScalar() + 1;
        if (isset($_POST['Channel']))
        {
            $channel->attributes = $_POST['Channel'];
            if ($channel->save())
                $this->redirect(array('/channels/view', 'id' => $channel->id));
        }
        $this->render('create', array('model' => $channel));
    }

    public function actionDelete($id)
    {
        $channel = self::loadModel(array('id' => $id));
        if (!$channel->delete())
            throw new CHttpException(500);
        $this->redirect(Yii::app()->request->urlReferrer);
    }

    public function actionSwitchHaveContract($id)
    {
        $model = $this->loadModel(array('id' => $id));
        $model->haveContract = intval(!$model->haveContract);
        if (!$model->save())
            throw new CHttpException(500);
        echo $model->haveContractString;
        Yii::app()->end();
    }

    public function actionSwitchIsMandatory($id)
    {
        $model = $this->loadModel(array('id' => $id));
        $model->isMandatory = intval(!$model->isMandatory);
        if (!$model->save())
            throw new CHttpException(500);
        echo $model->isMandatoryString;
        Yii::app()->end();
    }

    public function actionSwitchIsLicensed($id)
    {
        $model = $this->loadModel(array('id' => $id));
        $model->isLicensed = intval(!$model->isLicensed);
        if (!$model->save())
            throw new CHttpException(500);
        echo $model->isLicensedString;
        Yii::app()->end();
    }

    /**
     * @param $options
     * @return Channel
     * @throws CHttpException
     */
    public static function loadModel($options)
    {
        $model = Channel::model()->findByAttributes($options);
        if (!$model)
            throw new CHttpException(404);
        return $model;
    }

    public function filters()
    {
        return array(
            'accessControl',
        );
    }

    public function accessRules()
    {
        return array(
            array('allow', // allow authenticated users to access all actions
                'users'=>array('@'),
            ),
            array('deny'),
        );
    }

}

protected/controllers/ServersController.php
<?php

class ServersController extends Controller
{
    public function actionIndex()
    {
        $server = new Server('search');
        $server->unsetAttributes();
        if (isset($_REQUEST['Server']))
            $server->attributes = $_REQUEST['Server'];
        $this->render('index', array('model' => $server));
    }

    public function actionView($id, $showConfig = false)
    {
        $server = self::loadModel(array('id' => $id));
        $this->render('view', array('model' => $server, 'showConfig' => $showConfig));
    }

    public function actionUpdate($id)
    {
        $server = self::loadModel(array('id' => $id));
        if (isset($_POST['Server']))
        {
            $server->attributes = $_POST['Server'];
            $server->save();
        }
        $this->render('update', array('model' => $server));
    }

    public function actionCreate()
    {
        $server = new Server();
        if (isset($_POST['Server']))
        {
            $server->attributes = $_POST['Server'];
            if ($server->save())
                $this->redirect(array('/servers/view', 'id' => $server->id));
        }
        $this->render('create', array('model' => $server));
    }

    public function actionDelete($id)
    {
        $server = self::loadModel(array('id' => $id));
        if (!$server->delete())
            throw new CHttpException(500);
    }

    public function actionGetConfigs()
    {
        $server = Server::model()->findByAttributes(array('ip' => Yii::app()->request->userHostAddress));
        /* @var $server Server */
        if (!$server)
            throw new CHttpException(403);
        $tmpName = tempnam(sys_get_temp_dir(), 'aconf');
        $zip = new ZipArchive;
        $zip->open($tmpName, ZipArchive::CREATE || ZipArchive::OVERWRITE);
        foreach ($server->adapters as $adapter)
        {
            if ($adapter->dvbTranspoder)
            {
                $fileName = 'a'.$adapter->num.'.lua';
                $zip->addFromString($fileName, $adapter->configFile);
            }
        }
        if ($server->haveRelay)
            $zip->addFromString('relay.lua', $server->relayConfigFile);
        if ($server->haveUrlInput)
            for ($i = 0; $i < $server->urlInputProcesses; $i++)
                $zip->addFromString('urlInput_'.$i.'.lua', $server->getUrlInputsConfigFile($i));
        $zip->close();
        header("Content-type: application/octet-stream");
        header("Content-Disposition: attachment; filename=\"server.zip\"");
        echo file_get_contents($tmpName);
        unlink($tmpName);
        Yii::app()->end();
    }

    public function actionGetZabbixDiscovery()
    {
        $server = Server::model()->findByAttributes(array('ip' => Yii::app()->request->userHostAddress));
        /* @var $server Server */
        if (!$server)
            throw new CHttpException(403);
        $ret = array();
        foreach ($server->adapters as $adapter)
        {
            if ($adapter->dvbTranspoder)
                $ret[] = array(
                    '{#MAC}' => $adapter->mac,
                    '{#TRANS_NAME}' => $adapter->dvbTranspoder->description
                );
        }
        echo json_encode($ret, JSON_UNESCAPED_UNICODE);
        Yii::app()->end();
    }

    public static function loadModel($options)
    {
        $model = Server::model()->findByAttributes($options);
        if (!$model)
            throw new CHttpException(404);
        return $model;
    }

    public function filters()
    {
        return array(
            'ajaxOnly + delete',
            'accessControl',
        );
    }

    public function accessRules()
    {
        return array(
            array('allow', 'actions' => array('getConfigs', 'getZabbixDiscovery')),
            array('allow', // allow authenticated users to access all actions
                'users'=>array('@'),
            ),
            array('deny'),
        );
    }
}

protected/controllers/StreamsController.php
<?php

class StreamsController extends Controller
{
    public function actionIndex()
    {
        $stream = new Stream('search');
        $stream->unsetAttributes();
        if (isset($_REQUEST['Stream']))
            $stream->attributes = $_REQUEST['Stream'];
        $this->render('index', array('model' => $stream));
    }

    public function actionView($id)
    {
        $stream = self::loadModel(array('id' => $id));
        $this->render('view', array('model' => $stream));
    }

    public function actionUpdate($id)
    {
        $stream = self::loadModel(array('id' => $id));
        if (isset($_POST['Stream']))
        {
            $stream->attributes = $_POST['Stream'];
            $stream->save();
        }
        $this->render('update', array('model' => $stream));
    }

    public function actionCreate()
    {
        $stream = new Stream();
        if (isset($_POST['Stream']))
        {
            $stream->attributes = $_POST['Stream'];
            if ($stream->save())
                $this->redirect(array('/streams/view', 'id' => $stream->id));
        }
        $this->render('create', array('model' => $stream));
    }

    public function actionDelete($id)
    {
        $stream = self::loadModel(array('id' => $id));
        if (!$stream->delete())
            throw new CHttpException(500);
    }

    /**
     * @param $options
     * @return Stream
     * @throws CHttpException
     */
    public static function loadModel($options)
    {
        $model = Stream::model()->findByAttributes($options);
        if (!$model)
            throw new CHttpException(404);
        return $model;
    }

    public function filters()
    {
        return array(
            'ajaxOnly + delete',
            'accessControl',
        );
    }

    public function accessRules()
    {
        return array(
            array('allow', // allow authenticated users to access all actions
                'users'=>array('@'),
            ),
            array('deny'),
        );
    }

}

protected/views/layouts/_menu.php
<?php $this->widget('zii.widgets.CMenu',array(
    'items'=>array(
        array('label'=>Yii::t('menu','Серверы'), 'url'=>array('/servers/index'), 'visible' => !Yii::app()->user->isGuest),
        array('label'=>Yii::t('menu','Каналы'), 'url'=>array('/channels/index'), 'visible' => !Yii::app()->user->isGuest),
        array('label'=>Yii::t('menu','Потоки'), 'url'=>array('/streams/index'), 'visible' => !Yii::app()->user->isGuest),
        array('label'=>Yii::t('menu','Серверы ключей'), 'url'=>array('/softcamServers/index'), 'visible' => !Yii::app()->user->isGuest),
        array('label'=>Yii::t('menu','DVB трансподеры'), 'url'=>array('/transpoders/index'), 'visible' => !Yii::app()->user->isGuest),
        array('label'=>Yii::t('menu','DVB адаптеры'), 'url'=>array('/adapters/index'), 'visible' => !Yii::app()->user->isGuest),
        array('label'=>Yii::t('menu','Плейлист'), 'url'=>array('/playlist/index'), 'visible' => !Yii::app()->user->isGuest),
        array('label'=>Yii::t('menu','Мозаика каналов'), 'url'=>array('/mosaic'), 'visible' => !Yii::app()->user->isGuest),
        array('label'=>Yii::t('menu','Вход'), 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
        array('label'=>Yii::t('menu','Выход ({USER})', array('{USER}' => Yii::app()->user->name)), 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
    ),
));

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
    <h1><?php echo $this->pageHeader; ?></h1>
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/fullscreen.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />

    <title><?php echo CHtml::encode($this->pageHeader); ?></title>
</head>

<body>

<div class="container" id="page">

    <div id="mainmenu">
        <?php
        $this->renderPartial('//layouts/_menu');
        ?>
    </div><!-- mainmenu -->

    <?php echo $content; ?>

    <div class="clear"></div>

</div><!-- page -->

</body>
</html>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <!-- blueprint CSS framework -->
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
    <!--[if lt IE 8]>
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
    <![endif]-->

    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />

    <title><?php echo CHtml::encode($this->pageHeader); ?></title>
</head>

<body>

<div class="container" id="page">

    <div id="header">
        <div class="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
        <div class="logo fullscreenSwitch"><?php
            echo CHtml::link(
                CHtml::image(Yii::app()->assetManager->publish(Yii::app()->basePath.'/data/fullscreen.png')),
                $this->createUrl($this->route, CMap::mergeArray($_GET, array('fullscreen' => 1)))
            );
            ?></div>
    </div><!-- header -->
    <div id="mainmenu">
        <?php
        $this->renderPartial('//layouts/_menu');
        ?>
    </div><!-- mainmenu -->
    <?php if(isset($this->breadcrumbs)):?>
        <?php
        if(isset($this->breadcrumbs))
        {
            if ($this->pageHeader !== null)
                $this->breadcrumbs[] = $this->pageHeader;
            $this->widget('zii.widgets.CBreadcrumbs', array(
                'links'=>$this->breadcrumbs,
            ));
        }
        ?>
    <?php endif?>

    <?php echo $content; ?>

    <div class="clear"></div>

    <div id="footer">
        Copyright &copy; <?php echo date('Y'); ?> by <a href="http://cesbo.com/forum/user/185-abram/">Vadym Abramchuk</a> .<br/>
        All Rights Reserved.<br/>
        <?php echo Yii::powered(); ?>
    </div><!-- footer -->

</div><!-- page -->

</body>
</html>